### ISSUE TITLE
facter::fact doesn't work without passing facter::facts_hash

### ISSUE THREAD

**Issue by hunner** [ghoneycutt/puppet-module-facter#27]
These lines: https://github.com/ghoneycutt/puppet-module-facter/blob/v2.0.0/manifests/init.pp#L98 and https://github.com/ghoneycutt/puppet-module-facter/blob/v2.0.0/manifests/fact.pp#L16 cause the `facts.txt` file to not be managed if the `facts_hash` attribute is `undef` in the base class (ie, if I'm not using hiera).

Could you update make this usable where `facter::facts_hash` is not passed, but `facter::fact` defines don't need `file` passed? (perhaps always managing facts.txt in the base class)

**Comment by ghoneycutt** [comment]
If you move the file resource for facts_file out of the if statement so that it is always managed, but do not specify a hash of facts, then you would get /etc/facter/facts.d/facts.txt which would be empty. 

I believe your use case is that you want to call facter::fact from another class and have a few facts listed in facts.txt and not bother with different file names. I believe the solution above should work for that.

**Comment by ghoneycutt** [comment]
Fix in v3.0.0
